package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Switchman</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><h1><span>Stockyard</span> Switchman</h1><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main" id="list"></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2>New Deployment</h2>
<label class="fl">Service</label><input type="text" id="f-service" placeholder="Service"><label class="fl">Version</label><input type="text" id="f-version" placeholder="Version"><label class="fl">Environment</label><input type="text" id="f-environment" placeholder="Environment"><label class="fl">Strategy</label><input type="text" id="f-strategy" placeholder="Strategy"><label class="fl">Active Slot</label><input type="text" id="f-active_slot" placeholder="Active Slot"><label class="fl">Status</label><input type="text" id="f-status" placeholder="Status"><label class="fl">Deployed By</label><input type="text" id="f-deployed_by" placeholder="Deployed By"><label class="fl">Deployed At</label><input type="text" id="f-deployed_at" placeholder="Deployed At">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/deployments";
function showModal(){document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none"}
async function load(){const r=await fetch(API);const d=await r.json();const el=document.getElementById("list");if(!d.deployments||!d.deployments.length){el.innerHTML='<div class="empty">No deployments yet</div>';return}
el.innerHTML=d.deployments.map(e=>'<div class="item"><span class="del" onclick="del(\'{}'.replace('{}',e.id)+'\')">[x]</span><h3>${e.service}</h3><div class="item-meta"><span>${e.version||"—"}</span><span>${e.environment||"—"}</span><span>${e.strategy||"—"}</span><span>${e.active_slot||"—"}</span></div></div>').join("")}
async function save(){const body={"service":document.getElementById("f-service").value,"version":document.getElementById("f-version").value,"environment":document.getElementById("f-environment").value,"strategy":document.getElementById("f-strategy").value,"active_slot":document.getElementById("f-active_slot").value,"status":document.getElementById("f-status").value,"deployed_by":document.getElementById("f-deployed_by").value,"deployed_at":document.getElementById("f-deployed_at").value};await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load()
</script></body></html>` 